In [2]:
import numpy as np

### Multidimensional Array

Um array multidimensional é essencialmente, composto de listas de listas

In [39]:
array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                 [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                 [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', ' ']]])
print(array.shape)

(3, 3, 3)


> Para acessar os valores dentro dos arrays, podemos utilizar `chain indexing` ou `multidimensional indexing` através do NumPy, que é significativamente mais rápido. 

In [40]:
print(array[0][0][0]) # Chain indexing
print(array[0, 0, 0]) # Multidimensional indexing


nome = array[0, 0, 1] + array[1, 2, 2] + array[2, 0, 2] + array[1, 1, 1] + array[1, 1, 2] + array[2,2,2] + array[2, 0, 0]
print(nome)

A
A
BRUNO S


### Slicing

In [ ]:
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])

# print(array.ndim)
# print(array.shape)

# array[start:end:step]

# Selecionando linhas
print(array[0:4:2]) # end index é exclusivo, sempre indicar um index acima do que for exibido
print(array[::2])
print(array[::-1])

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [66]:
# Selecionando colunas
print(array[:,2])

print(array[:,2:4])

print(array[2,2:4])

[ 3  7 11 15]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]
[11 12]


### Aritmética
#### Escalar
Operações com um único valor aplicado em um array inteiro


In [69]:
array = np.array([1, 2, 3])

print(array + 2)
print(array * 2)
print(array // 2)

[3 4 5]
[2 4 6]
[0 1 1]


### Funções matemáticas vetorizadas
Aplicar funções em um array inteiro sem usar loop

In [79]:
array = np.array([25.0456, 9.789, 16.546])
print(np.sqrt(array))
print(np.round(array))
print(np.floor(array))
print(np.ceil(array))


[5.00455792 3.12873776 4.06767747]
[25. 10. 17.]
[25.  9. 16.]
[26. 10. 17.]


In [82]:
# Exemplo, cálculo de área de círculo

raio = np.array([5, 13.5, 2.8])

area = np.pi * raio ** 2
print(area)

[ 78.53981634 572.55526112  24.6300864 ]


### Element-wise arithmetic
As operações são aplicadas individualmente para cada elemento do array 

In [85]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


### Comparison operators
Criar arrays booleanos, comparar e filtrar dados e compará-los element-wise

In [ ]:
scores = np.array([91, 55, 82, 100, 64, 73])

print(scores == 100)
print(scores <= 60)

# Atribuindo valores para dados que atendem com determinada condição
scores[scores < 60] = 0
print(scores)

[False False False  True False False]
[False  True False False False False]
[ 91   0  82 100  64  73]


### Aggregate functions
Sintetiza a informação e normalmente retorna apenas um valor

In [100]:
print(np.var(scores))
print(np.std(scores))
print(np.min(scores)) 
print(np.argmax(scores)) # index do maior valor
print(np.mean(scores))
print(np.sum(scores))
print(array)
print(np.sum(array, axis=0)) # 0 - colunas, 1 - linhas

1068.888888888889
32.69386622730461
0
3
68.33333333333333
410
[25.0456  9.789  16.546 ]
51.3806


In [110]:
idades = np.array([[18, 13, 25, 15, 28, 35, 16, 19, 27, 33, 92],
         [17, 21, 27, 12, 9, 10, 8, 6, 8, 4, 85]])

teenagers = idades[(idades < 18) & (idades > 12)] # os operadores em NumPy são diferentes por ser baseado em C >> and == &, or == |
adults = idades[idades > 18]
seniors = idades[idades > 65]
par = idades[idades % 2 == 0]
impar = idades[idades % 2 != 0]

print(teenagers)
print(adults)
print(seniors)
print(par)
print(impar)

[13 15 16 17]
[25 28 35 19 27 33 92 21 27 85]
[92 85]
[18 28 16 92 12 10  8  6  8  4]
[13 25 15 35 19 27 33 17 21 27  9 85]


## Pandas
### Series
Pandas trabalha com "Series", as quais são compostas por arrays unidimensionais. Series podem conter diversos tipos de dados, booleano, int, float e str.
Quando criamos uma Series como `series = pd.Series(data)`, `Series` atua como constrututor (S maíusculo) e não como uma função. Series podem ser pensadas como uma coluna / planilha 1D ao invés de um array

In [111]:
import pandas as pd

In [118]:
data = [100, 102, 104, 200, 202]

series = pd.Series(data, index=['a', 'b', 'c', 'd', 'e']) # Se index é nulo, automaticamente é criado um index numérico com início em zero
print(series) 

a    100
b    102
c    104
d    200
e    202
dtype: int64


In [120]:
print(series.loc['c']) # a propriedade .loc encontra o valor que possui um determinado label (location by label)

print(series.iloc[2]) # a propriedade .iloc encontra o valor atrelado ao index (location by index)

print(series[series < 200])

104
104
a    100
b    102
c    104
dtype: int64


In [125]:
calories = {
    'Day 1' : 1750,
    'Day 2' : 2100,
    'Day 3' : 1700
}

# Dicionários são compostos de chave-valor, a chave funciona como index em uma Serie 
series = pd.Series(calories)
print(series)
print(series.loc['Day 2'])

series.loc['Day 3'] += 500
print(series.loc['Day 3'])

Day 1    1750
Day 2    2100
Day 3    1700
dtype: int64
2100
2200


In [127]:
print(series[series < 2000])

Day 1    1750
dtype: int64


# DataFrame

In [ ]:
data = {
    'Name' : ['Bob Esponja', 'Patrick Estrela', 'Lula Molusco'],
    'Age' : [30, 35, 50]
    }

df = pd.DataFrame(data, index = ['Employee 1', 'Employee 2', 'Employee 3']) # `DataFrame` é um construtor e não uma função, semelhante a `Series`

print(df.loc['Employee 1'])

print(df.iloc[2])





Name    Bob Esponja
Age              30
Name: Employee 1, dtype: object
Name    Lula Molusco
Age               50
Name: Employee 3, dtype: object
                       Name  Age      Job
Employee 1      Bob Esponja   30     Cook
Employee 2  Patrick Estrela   35      N/A
Employee 3     Lula Molusco   50  Cashier


In [ ]:
# Como adicionar uma coluna
df['Job'] = ['Cook', 'N/A', 'Cashier'] # o número de dados da coluna precisa ser igual ao número de observações / index 

print(df)

# Como adicionar uma linha
new_row = pd.DataFrame